version: '3.8'
services:
  mongodb: 
    image: mongo:latest
    volumes:
      - database:/data/db
  
  backend: 
    build: ./
    volumes:
      - data:/app/upload
    ports:
      - 8000:8000
    depends_on:
      - mongodb
volumes:
  database:
  data:
